-- Format for overwriting define values:

-- N MILITARY STUFFS
NDefines.NMilitary.CAVALRY_SPEED = 1.0

--N COUNTRY STUFFS
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 7
NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 12
NDefines.NCountry.SETTLMENT_GROWTH_CHANCE_MIN = 0.3
NDefines.NCountry.BASE_TARIFF = 0.25
NDefines.NCountry.TARIFF_LIBERTY_INCREASE = 0.50

--N COUNTRY STUFFS MAKES REBELS SCARIER
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_2_SIZE = 0.25

--N Culture Stuff
NDefines.NCountry.PS_CHANGE_CULTURE_OVERSEAS_RELIGION_MOD = -0.3
NDefines.NCountry.CULTURE_COST_DIFF_ADJACENT = -0.15
NDefines.NCountry.CULTURE_COST_DIFF_ORIGINAL = -0.15

--Fixes for diplomacy BS
NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 150
NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 250
NDefines.NDiplomacy.SUPPORT_REBELS_EFFECT = 20
NDefines.NDiplomacy.SUPPORT_REBELS_MONEY_FACTOR = 0.25
NDefines.NDiplomacy.SUPPORT_REBELS_COST = 40
NDefines.NDiplomacy.SUPPORT_REBELS_DURATION = 10


--Fixes for economy
NDefines.NEconomy.BASE_INTERESTS = 6
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 50
NDefines.NEconomy.AUTONOMY_AT_CONQUEST = 70
NDefines.NEconomy.AUTONOMY_AT_CONQUEST_CLAIM = 60
NDefines.NEconomy.EXPELLING_MINORITY_SETTLER_CHANCE_FACTOR = 0.08
NDefines.NEconomy.EXPELLED_MINORITY_DEV_BONUS_FACTOR = 0.3

--Fixes for stupid AI
NDefines.NAI.ONLY_INFANTRY_MERCS = 0
NDefines.NAI.CALL_IN_ALLIES_POWER_RATIO = 3
NDefines.NAI.DEVELOPMENT_CAP_BASE = 21
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1.5
NDefines.NAI.PEACE_TIME_MONTHS = 40



NDefines.NAI.MAX_CAV_PERCENTAGE = 75
NDefines.NAI.MIN_CAV_PERCENTAGE = 10
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 13