-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

-- N MILITARY STUFFS

NDefines.NMilitary.CAVALRY_SPEED = 1.0

--N AI STUFFS

--N COUNTRY STUFFS
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 7
NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 12
NDefines.NCountry.SETTLEMENT_GROWTH_CHECK_INTERVAL = 182
NDefines.NCountry.SETTLMENT_GROWTH_CHANCE_MIN = 0.2
NDefines.NCountry.BASE_TARIFF = 0.25
NDefines.NCountry.TARIFF_LIBERTY_INCREASE = 0.60

--N Culture Stuff
NDefines.NCountry.PS_CHANGE_CULTURE_OVERSEAS_RELIGION_MOD = -0.1
NDefines.NCountry.CULTURE_COST_DIFF_ADJACENT = -0.15
NDefines.NCountry.CULTURE_COST_DIFF_ORIGINAL = -0.15


--Fixes for diplomacy BS
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_LOSE = 0
NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 150
NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 250
NDefines.NDiplomacy.EXCOMMUNICATE_ACTION_MONTHS = 24
NDefines.NDiplomacy.SUPPORT_REBELS_EFFECT = 20
NDefines.NDiplomacy.SUPPORT_REBELS_MONEY_FACTOR = 0.25
NDefines.NDiplomacy.SUPPORT_REBELS_COST = 40
NDefines.NDiplomacy.SUPPORT_REBELS_DURATION = 10
NDefines.NDiplomacy.PEACE_COST_DISMANTLE_REVOLUTION = 60